### ISSUE TITLE
 pq: unknown authentication response

### ISSUE THREAD

**Issue by xQuai** [chop-dbhi/sql-agent#20]
Hello everyone,

I wanted to use the go program in combination with prometheus-sql to monitor a postgres database.
However, I get an error when trying to connect to the database.
following error:
`503 Service Unavailable: problem connecting to database: pq: unknown authentication response: 10`

Is it possible that the problem occurs due to a postgres go library that is too old in combination with a database version that is too new?

If so, could you please update the Postgres library in the program?

The Postgres go library used in this program is from 2018.

Regards,
xQuai

**Comment by bruth** [comment]
Hi @xQuai, it certainly is possible. We are going to do a round of development shortly to get everything updated.

**Comment by xQuai** [comment]
Thank you. 👍

**Comment by brokenintuition** [comment]
Hi @xQuai,

We've pushed a new version with the updated postgres library (and a few other updates) to [dbhi/sql-agent:latest](https://hub.docker.com/r/dbhi/sql-agent/tags). Please try out the new version. Thanks!

**Comment by xQuai** [comment]
Hi @brokenintuition,

its working for me now. Thank you. 🙂

**Comment by VladoDemcak** [comment]
looks like the issue is still there for postgres 14. however the latest  [dbhi/sql-agent:latest](https://hub.docker.com/r/dbhi/sql-agent/tags) version from Jun 2022 works well with postgres 13.7.

@brokenintuition

**Comment by brokenintuition** [comment]
@VladoDemcak my apologies, I never actually committed the `lib/pq` version update in the last change and tested with a database that was old enough that I didn't catch it. I pushed a new version to [dbhi/sql-agent:latest](https://hub.docker.com/r/dbhi/sql-agent/tags) that appears to work with postgres 14
